server:
  servlet:
    context-path: /people
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db_people
    username: postgres
    password: developer
  sql:
    init:
      platform: postgres